### ISSUE TITLE
readme.html怎么生成的？

### ISSUE THREAD

**Issue by cwt9562** [MOxFIVE/MOxFIVE.github.io#2]
我的source文件夹下有一个readme.md，然后hexo会给生成一个readme.html，可是这个html里是各种标签，能问下你的这个是什么弄的么？
我的repo[https://github.com/cwt9562/cwt9562.github.io](https://github.com/cwt9562/cwt9562.github.io)

**Comment by MOxFIVE** [comment]
**方法一：**
不用 md，直接把 README.html 放在主题 source 根目录（此时 Hexo/source 根目录下不要有 README 文件），内容如下
https://github.com/MOxFIVE/M-Hexo-Blog/blob/master/themes/iyelee/source/README.html

**方法二：**
Hexo 配置 `skip_render: /README.md`，然后把 `README.md` 放在 `Hexo/source` 根目录下

**Comment by cwt9562** [comment]
方法1不知道为什么是会被渲染, 可能跟我的hexo版本有关系
我用了方法2, 然后skip_render属性值里不带'/'
skip_render: README.md  这样

**Comment by cwt9562** [comment]
感谢
